-- STATES TABLE
CREATE DATABASE
IF NOT EXISTS hbtn_0d_usa;

USE hbnt_0d_usa;

CREATE TABLE
IF NOT EXISTS hbnt_0d_usa.states (
  id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  name VARCHAR(256) NOT NULL,
  );
